language: php

php:
    - 5.5

before_script:
  - sudo apt-get install -y php5-geoip
  - pear install PHP_CodeSniffer-2.0.0RC2
  - phpenv rehash
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.0-beta4" --no-interaction
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - ./phpcs.sh
